### ISSUE TITLE
NullPointerException when EasyForm contains other Views

### ISSUE THREAD

**Issue by Harti** [emmasuzuki/EasyForm#6]
First of all, many thanks for making this great library. It just *works* and does its job perfectly so far. I've tried other libs but they are usually abandoned, tailored for Android 2 or not even remotely as smooth as yours.

I have a crash issue using other (Non-Easy-)Views within an EasyForm wrapper when my EasyTextInputLayout is being validated. In my layout file (see below) I am using a Number Picker library which might act like a hidden form input field but doesn't conform to your library's input fields.

Maybe an `instanceof` check is needed.

`layout.xml`
```
    <com.emmasuzuki.easyform.EasyForm
            android:id="@+id/form_room"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:submitButton="@+id/form_room_submit"
            app:showErrorOn="unfocus">

        <com.emmasuzuki.easyform.EasyTextInputLayout
                android:id="@+id/form_room_name"
                android:hint="@string/form_room_name"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

        <LinearLayout
                android:id="@+id/form_room_group_number_floor"
                android:layout_below="@id/form_room_name"
                android:orientation="horizontal"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

            <com.emmasuzuki.easyform.EasyTextInputLayout
                    android:id="@+id/form_room_number"
                    android:hint="@string/form_room_number"
                    android:layout_width="0dp"
                    android:layout_weight="3"
                    android:layout_height="wrap_content"
                    android:layout_below="@id/form_room_name"
                    app:errorMessage="@string/form_error_empty"
                    app:errorType="empty" />

            <com.shawnlin.numberpicker.NumberPicker
                    android:id="@+id/form_room_floor"
                    android:hint="@string/form_room_floor"
                    android:layout_width="0dp"
                    android:layout_weight="2"
                    android:layout_height="wrap_content"
                    android:layout_below="@id/form_room_number"
                    app:np_orientation="horizontal"
                    app:np_min="-3"
                    app:np_max="8"
                    app:np_value="0" />
        </LinearLayout>

        <Button
                android:id="@+id/form_room_submit"
                android:text="@string/form_room_submit"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_below="@id/form_room_group_number_floor" />

    </com.emmasuzuki.easyform.EasyForm>
``` 

Following exception is thrown:
```
java.lang.NullPointerException: Attempt to write to field 'boolean com.emmasuzuki.easyform.EasyForm$FormInputs.isValid' on a null object reference
                                                                          at com.emmasuzuki.easyform.EasyForm.onError(Unknown Source)
                                                                          at com.emmasuzuki.easyform.EasyTextInputLayout.validate(Unknown Source)
                                                                          at com.emmasuzuki.easyform.EasyTextInputLayout.onFocusChange(Unknown Source)
                                                                          at android.view.View.onFocusChanged(View.java:5207)
                                                                          at android.widget.TextView.onFocusChanged(TextView.java:7916)
                                                                          at android.view.View.clearFocusInternal(View.java:5090)
                                                                          at android.view.View.unFocus(View.java:5123)
```

Thanks in advance,

Harti

**Comment by emmasuzuki** [comment]
Hi Harti, I am glad that my library helps your app. 

I found out the issue is I am mistakenly clearing the internal `SparseArray` (which is used to track which fields are valid or invalid) inside of recursive function. The recursion occurs on any child `ViewGroup`. In your case, both `LinearLayout (form_room_group_number_floor )` and `NumberPicker` are `ViewGroup`.

I try to release the new version soon with the new feature and this fix. 
Though, in a mean time, here is a workaround.

```xml
<com.emmasuzuki.easyform.EasyForm
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/form_room"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:submitButton="@+id/form_room_submit"
    app:showErrorOn="unfocus">

    <com.shawnlin.numberpicker.NumberPicker
        android:id="@+id/form_room_floor"
        android:hint="@string/form_room_floor"
        android:layout_width="200dp"
        android:layout_height="wrap_content"
        android:layout_below="@+id/form_room_number"
        app:np_orientation="horizontal"
        app:np_min="-3"
        app:np_max="8"
        app:np_value="0" />
      
    <com.emmasuzuki.easyform.EasyTextInputLayout
        android:id="@id/form_room_number"
        android:hint="form_room_number"
        android:layout_width="200dp"
        android:layout_height="wrap_content"
        android:layout_below="@+id/form_room_name"
        app:errorMessage="@string/error_message_empty"
        app:errorType="empty" />

    <com.emmasuzuki.easyform.EasyTextInputLayout
        android:id="@id/form_room_name"
        android:hint="form_room_name"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    <Button
        android:id="@+id/form_room_submit"
        android:text="@string/submit"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/form_room_floor" />

</com.emmasuzuki.easyform.EasyForm>
```

**Comment by Harti** [comment]
Awesome, thanks for fixing this so fast! 

You might need to build and create another release though before it's possible to import via Gradle.
